EPC-PolarBearSaver9000/EPC PolarBearSaver9001/Controllers/SocialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DBContext.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using System.Data.Entity;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EPC_PolarBearSaver9001.Controllers
{
    public class SocialController : Controller
    {
        #region Properties

        private readonly DBContext.Models.EPC_PolarBearSaver9001Context _context = DBContext.ContextBuilder.GetContext();
        private IHttpContextAccessor HttpContextAccessor { get; set; }

        private AspNetUsers _loggedInUser;
        private AspNetUsers LoggedInUser
        {
            get
            {
                if(_loggedInUser == null && HttpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier) != null)
                {
                    var userId = HttpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    _loggedInUser = _context.AspNetUsers.Where(n => n.Id == userId).Single();
                }
                return _loggedInUser;
            }
        }
        #endregion

        #region Constructor     

        public SocialController(IHttpContextAccessor httpContextAccessor)
        {
            this.HttpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region Actions
        public IActionResult Index()
        {
            if(LoggedInUser != null)
            {
                Models.SocialModel model = CreateNewModel();
                return View(model);
            }
            return View("UnAuthorised");
        }

        [HttpPost]
        public IActionResult Index(string searchQuery)
        {
            Models.SocialModel model = CreateNewModel();
            model.SearchResults = GetSearchResults(searchQuery, model);
            return View(model);
        }

        [HttpPost]
        [ActionName("AddFriend")]
        public IActionResult AddFriend(string userID)
        {
            AspNetUsers friendToAdd = _context.AspNetUsers.Where(n => n.Id == userID).Single();
            var newFriends = new Friends()
            {
                User1 = LoggedInUser,
                User2 = friendToAdd
            };
            _context.Add(newFriends);
            _context.SaveChanges();
            Models.SocialModel model = CreateNewModel();
            return View("Index", model);
        }

        [HttpPost]
        [ActionName("RemoveFriend")]
        public IActionResult RemoveFriend(string userID)
        {
            Friends friendToRemove = _context.Friends.Where(n =>n.User1Id == LoggedInUser.Id && n.User2Id == userID).First();
            _context.Remove(friendToRemove);
            _context.SaveChanges();
            Models.SocialModel model = CreateNewModel();
            return View("Index", model);
        }
        #endregion

        #region Private Methods

        private List<AspNetUsers> GetSearchResults(string searchQuery, Models.SocialModel model)
        {
            List<AspNetUsers> usersToExclude = new List<AspNetUsers>();
            usersToExclude.AddRange(model.Friends);
            usersToExclude.Add(LoggedInUser);

            return _context.AspNetUsers.Where(n => n.UserName.Contains(searchQuery))
                                .Except(usersToExclude).ToList();
        }

        private Models.SocialModel CreateNewModel()
        {
            Models.SocialModel model = new Models.SocialModel
            {
                Friends = _context.Friends.Where(n => n.User1Id == LoggedInUser.Id)
                                          .Select(n => n.User2)
                                          .Include(n=>n.Address)
                                          .ToList(),
                SearchResults = new List<AspNetUsers>()
            };
            return model;
        }
        #endregion

    }
}

EPC-PolarBearSaver9000/EPC PolarBearSaver9001/Views/Shared/UnAuthorised.cshtml
@{
    ViewData["Title"] = "UnAuthorised";
}

<center>
    <img src="~/images/Carlos.png" />
    <h1>Stop right there!</h1>
    <h2>Carlos does not recognise you! Try signing in before entering this page.</h2>
</center>

EPC-PolarBearSaver9000/EPC PolarBearSaver9001/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EPC_PolarBearSaver9001</title>

        <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="height: 110px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img id="CarlosImg" src="~/images/professionalLogo69.png" style="height: 85px;" />
                </a>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="padding-left:150px; padding-top:30px;">
                    EPC PolarBearSaver9001
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Social" asp-action="Index">Social</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="RewardsPage">Rewards</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" style="padding-top:150px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - EPC_PolarBearSaver9001</p>
        </footer>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>